
-- consulta Gio
-- lista o nome dos animais que receberam a vacina de raiva
-- Junta as tabelas ANIMAL, CARTEIRA_VACINA e VACINA 
-- filtra os registros onde a vacina aplicada é "Raiva" 
SELECT A.NOME, A.NASCIMENTO
FROM ANIMAL A JOIN CARTEIRA_VACINA CV ON A.ID_MICROCHIP = CV.ANIMAL_ID_MICROCHIP JOIN VACINA V ON CV.ID_CARTEIRA_VACINA = V.ID_CARTEIRA_VACINA 
WHERE UPPER(V.NOME_VACINA) = 'RAIVA';

-- Nome do animal mais velho
-- Subconsulta Simples e Escalar
SELECT A.NOME AS NOME_ANIMAL
FROM ANIMAL A
WHERE A.NASCIMENTO = (
               SELECT MIN(NASCIMENTO)
               FROM ANIMAL
)
;

-- CONSULTA LUMA
-- TUTORES QUE TEM MAIS DE DOIS ANIMAIS E A QUANTIDADE DE ANIMAIS QUE ELE POSSUI
-- JUNTA TABELA TUTOR, PESSOA E RESPONSAVEL 
-- USA GROUP BY E HAVING 
SELECT P.NOME AS NOME_TUTOR, COUNT(R.ID_MICROCHIP) AS QNT_ANIMAIS 
FROM RESPONSAVEL R 
JOIN TUTOR T ON R.TUTOR_CPF = T.CPF 
JOIN PESSOA P ON T.CPF = P.CPF 
GROUP BY P.NOME 
HAVING COUNT(R.ID_MICROCHIP) > 2; 

-- PESSOA CADASTRADA NO SISTEMA QUE NÃO É TUTOR NEM VETERINÁRIO 
-- ANTI JOIN E RETORNA LISTA 
SELECT P.NOME AS NOME 
FROM PESSOA P 
WHERE P.CPF NOT IN (SELECT CPF FROM TUTOR) 
AND P.CPF NOT IN (SELECT CPF FROM VETERINARIO); 

-- Consulta Mari
-- Agrupa os veterinários que passaram mais de uma receita 
SELECT P.NOME 
FROM PESSOA P JOIN VETERINARIO V
ON P.CPF = V.CPF JOIN RECEITA R ON R.VET_CPF = V.CPF 
GROUP BY R.VET_CPF
HAVING COUNT(*) > 1
;

-- CONSULTA LETI
-- TODAS AS PESSOAS CADASTRADAS, JUNTO COM O NUMERO DE TELEFONE (SE HOUVER)
-- JUNTA TABELA PESSOA E TEL_PESSOA 
-- USA LEFT JOIN 
SELECT P.NOME, T.NUM_TELEFONE
FROM PESSOA P
LEFT JOIN TEL_PESSOA T ON P.CPF = T.PESSOA_CPF; 

-- CONSULTA JULYANA
-- Seleciona todos os animais cujo ID_MICROCHIP está na lista de
-- IDs de animais da tabela CONSULTA
-- Versão com IN
SELECT A.NOME, A.NASCIMENTO
FROM ANIMAL A
WHERE A.ID_MICROCHIP IN (
        SELECT C.ANIMAL_ID_MICROCHIP
        FROM CONSULTA C
);

-- Versão com EXISTS
SELECT A.NOME, A.NASCIMENTO
FROM ANIMAL A
WHERE EXISTS (
        SELECT 1
        FROM CONSULTA C
        WHERE C.ANIMAL_ID_MICROCHIP = A.ID_MICROCHIP
);


