CREATE TABLE PESSOA(
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(50),
    NASCIMENTO DATE,
    END_LOGRADOURO VARCHAR(15),
    END_NUMERO VARCHAR(10),
    END_BAIRRO VARCHAR(25),
    END_CIDADE VARCHAR(25),
    END_UF VARCHAR(20),
    END_CEP VARCHAR(8),
);

CREATE TABLE TEL_PESSOA(
    NUM_TELEFONE VARCHAR(12),
    PESSOA_CPF VARCHAR(11),
    CONSTRAINT FK_CPF_PESSOA FOREIGN KEY (PESSOA_CPF) REFERENCES PESSOA (CPF) ON DELETE CASCADE
    CONSTRAINT PK_TEL_PESSOA PRIMARY KEY (NUM_TELEFONE, PESSOA_CPF)
);

CREATE TABLE ESPECIALIDADE(
    ID_ESPECIALIDADE VARCHAR(10) PRIMARY KEY,
    NOME_ESP VARCHAR(15)
);

CREATE TABLE CONSULTORIO(
    CNPJ VARCHAR(16) PRIMARY KEY,
    NOME VARCHAR(50),
    ENDERECO VARCHAR(50)
);

CREATE TABLE VETERINARIO(
    CPF VARCHAR(11) PRIMARY KEY,
    CRMV VARCHAR(15),
    SUPERVISOR_CPF VARCHAR(11),
    CONSTRAINT FK_SUPERVISOR_CPF FOREIGN KEY (SUPERVISOR_CPF) REFERENCES VETERINARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_VET_CPF FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE

);

CREATE TABLE TUTOR(
    CPF VARCHAR(11) PRIMARY KEY,
    CONSTRAINT FK_TUTOR_CPF FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);

CREATE TABLE ESPECIALIDADE_VET(
    VET_CPF VARCHAR(11),
    ESPECIALIDADE_ID VARCHAR(11),
    CONSTRAINT PK_ESPECIALIDADE PRIMARY KEY (VET_CPF, ESPECIALIDADE_ID),
    CONSTRAINT FK_VET_CPF  FOREIGN KEY (VET_CPF) REFERENCES VETERINARIO(VET_CPF) ON DELETE CASCADE
);

CREATE TABLE ANIMAL(
    ID_MICROCHIP VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(20),
    SEXO VARCHAR(1),
    TUTOR_CPF VARCHAR(11) NOT NULL,
    NASCIMENTO DATE,
    CONSTRAINT FK_TUTOR_CPF FOREIGN KEY (TUTOR) REFERENCES TUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE CONSULTA(
    MOMENTO_CONSULTA TIMESTAMP,
    VET_CPF VARCHAR(11),
    ANIMAL_ID_MICROCHIP VARCHAR(15),
    CONSULTORIO_CNPJ VARCHAR(16) NOT NULL,
    CONSTRAINT PK_CONSULTA PRIMARY KEY (MOMENTO_CONSULTA, VET_CPF, ANIMAL_ID_MICROCHIP),
    CONSTRAINT FK_VET_CPF FOREIGN KEY (VET_CPF) REFERENCES VETERINARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_ANIMAL_ID_MICROCHIP FOREIGN KEY (ANIMAL_ID_MICROCHIP) REFERENCES ANIMAL(ID_MICROCHIP) ON DELETE CASCADE
    CONSTRAINT FK_CONSULTORIO_CNPJ FOREIGN KEY (CONSULTORIO_CNPJ) REFERENCES CONSULTORIO(CNPJ)
);

CREATE TABLE RECEITA(
    INSTRUCAO VARCHAR(50),
    MOMENTO_CONSULTA DATETIME,
    VET_CPF VARCHAR(11),
    ANIMAL_ID VARCHAR(15),
    INSTANTE_EMISSAO TIMESTAMP,
    CONSTRAINT PK_RECEITA PRIMARY KEY (MOMENTO_CONSULTA, VET_CPF, ANIMAL_ID, INSTANTE_EMISSAO),
    

);

CREATE TABLE INTERNACAO(
    ID_INTERNACAO PRIMARY KEY VARCHAR(10),
    MOMENTO_ENTRADA DATETIME,
    ANIMAL_ID_MICROCHIP VARCHAR(15),
    MOTIVO_INTERCAO VARCHAR(50),
    CONSTRAINT FK_ANIMAL_ID_MICROCHIP FOREIGN KEY (ANIMAL_ID_MICROCHIP) REFERENCES ANIMAL(ID_MICROCHIP) ON DELETE CASCADE
);

CREATE TABLE REGISTRO_DIARIO(
    ID_INTERNACAO VARCHAR(10),
    MOMENTO_REGISTRO DATETIME,
    OBSERVACOES VARCHAR(50),
    CONSTRAINT FK_ID_INTERNACAO FOREIGN KEY (ID_INTERNACAO) REFERENCES INTERNACAO(ID_INTERNACAO) ON DELETE CASCADE,
    CONSTRAINT PK_REGISTRO PRIMARY KEY (ID_INTERNACAO, MOMENTO_REGISTRO
    )
);

CREATE TABLE FICHA_EMERGENCIA(
    ID_FICHA VARCHAR(10) PRIMARY KEY,
    TEL_EMERGENCIA VARCHAR(60),
    AUTORIZACAO_PROCEDIMENTO VARCHAR(60),
    ANIMAL_ID_MICROCHIP VARCHAR(15) UNIQUE NOT NULL,
    CONSTRAINT FK_ANIMAL_ID_MICROCHIP FOREIGN KEY (ANIMAL_ID_MICROCHIP) REFERENCES ANIMAL(ID_MICROCHIP)
);

->