/* DDL - Oracle Friendly */

CREATE TABLE PESSOA (
    CPF VARCHAR2(11) PRIMARY KEY,
    NOME VARCHAR2(50),
    NASCIMENTO DATE,
    END_LOGRADOURO VARCHAR2(50), /* Aumentei o tamanho para mais flexibilidade */
    END_NUMERO VARCHAR2(10),
    END_BAIRRO VARCHAR2(25),
    END_CIDADE VARCHAR2(25),
    END_UF VARCHAR2(20),
    END_CEP VARCHAR2(8)
);

CREATE TABLE TEL_PESSOA (
    NUM_TELEFONE VARCHAR2(12),
    PESSOA_CPF VARCHAR2(11),
    CONSTRAINT PK_TEL_PESSOA PRIMARY KEY (NUM_TELEFONE, PESSOA_CPF),
    CONSTRAINT FK_CPF_PESSOA FOREIGN KEY (PESSOA_CPF) REFERENCES PESSOA (CPF) ON DELETE CASCADE
);

CREATE TABLE CONSULTORIO (
    CNPJ VARCHAR2(16) PRIMARY KEY,
    NOME VARCHAR2(50),
    ENDERECO VARCHAR2(50)
);

CREATE TABLE VETERINARIO (
    CPF VARCHAR2(11) PRIMARY KEY,
    CRMV_UF VARCHAR2(2),
    CRMV_NUM VARCHAR2(4),
    SUPERVISOR_CPF VARCHAR2(11),
    CONSTRAINT FK_SUPERVISOR_CPF FOREIGN KEY (SUPERVISOR_CPF) REFERENCES VETERINARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_VET_CPF FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE,
    CHECK (UPPER(CRMV_UF) = 'PE')
);

CREATE TABLE ESPECIALIDADE (
    VET_CPF VARCHAR2(11),
    NOME_ESP VARCHAR2(15),
    CONSTRAINT FK_CPF_VET FOREIGN KEY (VET_CPF) REFERENCES VETERINARIO (CPF) ON DELETE CASCADE,
    CONSTRAINT PK_ESPECIALIDADE PRIMARY KEY (VET_CPF, NOME_ESP)
);

CREATE TABLE TUTOR (
    CPF VARCHAR2(11) PRIMARY KEY,
    CONSTRAINT FK_TUTOR_CPF FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);

CREATE TABLE ANIMAL (
    ID_MICROCHIP NUMBER(10) PRIMARY KEY, /* Alterado de INT(10) para NUMBER(10) */
    NOME VARCHAR2(20),
    SEXO VARCHAR2(1),
    NASCIMENTO DATE
);

CREATE TABLE RESPONSAVEL (
    ID_MICROCHIP NUMBER(10), /* Alterado de INT(10) para NUMBER(10) */
    TUTOR_CPF VARCHAR2(11),
    CONSTRAINT FK_TUTOR_CPF_RESP FOREIGN KEY (TUTOR_CPF) REFERENCES TUTOR(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_ID_MICROCHIP_RESP FOREIGN KEY (ID_MICROCHIP) REFERENCES ANIMAL(ID_MICROCHIP) ON DELETE CASCADE,
    CONSTRAINT PK_RESPONSAVEL PRIMARY KEY (TUTOR_CPF, ID_MICROCHIP)
);

CREATE TABLE CONSULTA (
    MOMENTO_CONSULTA TIMESTAMP,
    VET_CPF VARCHAR2(11),
    ANIMAL_ID_MICROCHIP NUMBER(10), /* Alterado de INT(10) para NUMBER(10) */
    CONSULTORIO_CNPJ VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_CONSULTA PRIMARY KEY (MOMENTO_CONSULTA, VET_CPF, ANIMAL_ID_MICROCHIP),
    CONSTRAINT FK_VET_CPF_CONS FOREIGN KEY (VET_CPF) REFERENCES VETERINARIO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_ANIMAL_ID_MICROCHIP_CONS FOREIGN KEY (ANIMAL_ID_MICROCHIP) REFERENCES ANIMAL(ID_MICROCHIP) ON DELETE CASCADE,
    CONSTRAINT FK_CONSULTORIO_CNPJ FOREIGN KEY (CONSULTORIO_CNPJ) REFERENCES CONSULTORIO(CNPJ)
);

CREATE TABLE RECEITA (
    INSTRUCAO VARCHAR2(50),
    ID_RECEITA NUMBER(10) PRIMARY KEY, /* Alterado de INT(10) para NUMBER(10) */
    MOMENTO_CONSULTA TIMESTAMP,
    VET_CPF VARCHAR2(11),
    ANIMAL_ID_MICROCHIP NUMBER(10), /* CORRIGIDO: Nome e tipo da coluna para corresponder à FK */
    CONSTRAINT FK_CONSULTA_RECEITA FOREIGN KEY (MOMENTO_CONSULTA, VET_CPF, ANIMAL_ID_MICROCHIP) /* CORRIGIDO */
        REFERENCES CONSULTA(MOMENTO_CONSULTA, VET_CPF, ANIMAL_ID_MICROCHIP)
);

CREATE TABLE INTERNACAO (
    MOMENTO_ENTRADA TIMESTAMP,
    ANIMAL_ID_MICROCHIP NUMBER(10), /* Alterado de INT(10) para NUMBER(10) */
    MOTIVO_INTERNACAO VARCHAR2(50), /* Corrigido o nome da coluna de 'INTERCAO' para 'INTERNACAO' */
    CONSTRAINT FK_ANIMAL_ID_MICROCHIP_INT FOREIGN KEY (ANIMAL_ID_MICROCHIP) REFERENCES ANIMAL(ID_MICROCHIP) ON DELETE CASCADE,
    CONSTRAINT PK_INTERNACAO PRIMARY KEY (ANIMAL_ID_MICROCHIP, MOMENTO_ENTRADA)
);

CREATE TABLE REGISTRO_DIARIO (
    MOMENTO_REGISTRO TIMESTAMP,
    ANIMAL_ID_MICROCHIP NUMBER(10), /* Alterado de INT(10) para NUMBER(10) */
    MOMENTO_ENTRADA TIMESTAMP,
    OBSERVACOES VARCHAR2(50),
    CONSTRAINT FK_INTERNACAO_REG FOREIGN KEY (ANIMAL_ID_MICROCHIP, MOMENTO_ENTRADA)
        REFERENCES INTERNACAO (ANIMAL_ID_MICROCHIP, MOMENTO_ENTRADA) ON DELETE CASCADE,
    CONSTRAINT PK_REGISTRO PRIMARY KEY (ANIMAL_ID_MICROCHIP, MOMENTO_ENTRADA, MOMENTO_REGISTRO)
);

CREATE TABLE CARTEIRA_VACINA (
    ID_CARTEIRA_VACINA NUMBER(10) PRIMARY KEY, /* Alterado de INT(10) para NUMBER(10) */
    ANIMAL_ID_MICROCHIP NUMBER(10) NOT NULL UNIQUE, /* Alterado de INT(10) para NUMBER(10) */
    CONSTRAINT FK_ANIMAL_ID_MICROCHIP_CART FOREIGN KEY (ANIMAL_ID_MICROCHIP) REFERENCES ANIMAL(ID_MICROCHIP) ON DELETE CASCADE
);

CREATE TABLE VACINA (
    NOME_VACINA VARCHAR2(15),
    VALIDADE DATE,
    ID_CARTEIRA_VACINA NUMBER(10), /* Alterado de INT(10) para NUMBER(10) */
    CONSTRAINT FK_ID_CARTEIRA_VACINA FOREIGN KEY (ID_CARTEIRA_VACINA) REFERENCES CARTEIRA_VACINA(ID_CARTEIRA_VACINA),
    CONSTRAINT PK_VACINA PRIMARY KEY (ID_CARTEIRA_VACINA, NOME_VACINA)
);